const GET_PHOTOS = 'PHOTOS/GET_PHOTOS'
const PHOTOS_LOADING_START = 'PHOTOS/LOADING_START'
const PHOTOS_LOADED = 'PHOTOS/LOADED'
const PHOTOS_LOADING_END = 'PHOTOS/LOADING_END'
const PHOTOS_LOADING_ERROR = 'PHOTOS/LOADING_ERROR'

const types = {
	GET_PHOTOS,
	PHOTOS_LOADING_START,
	PHOTOS_LOADED,
	PHOTOS_LOADING_END,
	PHOTOS_LOADING_ERROR,
}

export default types
